language: php

php:
  - 7.1
  - 7.2
  - 7.3
  - 7.4

before_script:
  - ./tests/install-extension.sh
  - composer update --dev
  - phpenv config-rm xdebug.ini
  - composer update
  - phpenv rehash

script:
  - php ./vendor/bin/phpcs
  - php ./vendor/bin/phpunit --testsuite=all

after_failure:
  - sudo apt-get -qq install gdb
  - gdb -quiet -command=framework/tests/ci/gdb --args $(phpenv which php) vendor/bin/phpunit --debug --colors --testsuite=all